"""The observability middleware (PH2.5).

WHY ONE MIDDLEWARE AND NOT THREE
--------------------------------
Request-ID assignment, metrics recording and access logging are three concerns,
and the tidy instinct is three middlewares. That instinct is wrong here. Every
ASGI middleware is a real per-request cost — an extra frame, an extra `send`
wrapper closure around the response stream, an extra `await` — paid by every
request on every route, forever. The three concerns also share exactly the same
data (start time, request ID, final status, resolved route), so splitting them
means either computing that data three times or passing it between layers
through the scope. One middleware, one timer, one closure.

WHY IT IS REGISTERED LAST (AND SO RUNS FIRST)
---------------------------------------------
Starlette runs middleware in reverse registration order, so the last one added
is the outermost. This one must be outermost, for three reasons:

1. **The request ID must exist before anything else can log.** The CSRF
   middleware, the rate limiter and the audit logger all emit records; if they
   ran outside this one, their lines would have no correlation ID — and they are
   precisely the lines you most want correlated, because they describe rejected
   requests.
2. **Rejections must be counted.** A rate-limited 429 or a CORS-rejected request
   never reaches a route handler. Instrumentation placed inside those layers
   would report a healthy service while the front door was returning errors to
   every user — the exact scenario where metrics are supposed to be the alarm.
3. **`X-Request-ID` must be on every response**, including the ones generated by
   an inner middleware, so a user reporting *any* error has an ID to quote.

Resulting execution order (see `server.py` for the full pipeline):

    Observability → Security Headers → CORS → Rate Limiter → CSRF → route

WHY PURE ASGI AND NOT `BaseHTTPMiddleware`
------------------------------------------
Starlette's `BaseHTTPMiddleware` buffers the response body to hand it over as a
`Response` object, which breaks streaming and adds allocation per request. It
also runs the downstream app in a separate task, which would put the downstream
handler in a *different* context from the one this middleware bound — silently
losing the request ID for every log line inside every route handler, i.e. the
entire point of the module. The pure-ASGI form (matching
`security.headers.SecurityHeadersMiddleware`) has neither problem: `contextvars`
set here are visible downstream because it is all one task.
"""
from __future__ import annotations

import time
from typing import Optional

from starlette.datastructures import MutableHeaders
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from observability import context, metrics
from observability import logging as obs_logging

# Route label for a request that matched no route (404s, and every scanner
# probing for `/wp-admin`). Collapsing them into one bucket is what stops a
# scanner from creating an unbounded number of metric series — see the
# cardinality discussion in `observability.metrics`.
UNMATCHED_ROUTE = "<unmatched>"

# Paths whose access log lines are suppressed unless LOG_HEALTH_REQUESTS=1.
# Metrics are still recorded for them; only the narration is dropped.
_PROBE_PATH_PREFIXES = ("/api/health",)
_PROBE_PATHS = frozenset({"/api", "/api/metrics"})


def route_template(scope: Scope) -> str:
    """The matched route's *template*, e.g. `/api/trades/{trade_id}`.

    Starlette's router writes the matched `Route` object into the scope as it
    dispatches, and because the scope dict is mutated in place, it is visible
    here once the downstream call returns. `path_format` is the templated form;
    `path` is the fallback for route types that lack it.

    This function is the single most important line of cardinality defence in
    the codebase: returning `scope["path"]` instead would create one metric
    series per trade ID, per user ID and per scanned URL.
    """
    route = scope.get("route")
    if route is not None:
        template = getattr(route, "path_format", None) or getattr(route, "path", None)
        if template:
            return str(template)
    return UNMATCHED_ROUTE


def _client_ip(scope: Scope) -> Optional[str]:
    """Best-effort client IP, matching how `security.rate_limit` attributes one.

    Honours the first hop of `X-Forwarded-For` when present so that a
    deployment behind a load balancer logs the user's address rather than the
    balancer's; falls back to the socket peer. Consistency with the rate limiter
    and the audit log matters more than absolute accuracy — three subsystems
    disagreeing about who made a request makes all three untrustworthy.
    """
    try:
        for key, value in scope.get("headers", ()):
            if key == b"x-forwarded-for":
                first = value.decode("latin-1").split(",")[0].strip()
                if first:
                    return first
        client = scope.get("client")
        return client[0] if client else None
    except Exception:  # pragma: no cover - defensive
        return None


def _header(scope: Scope, name: bytes) -> Optional[str]:
    try:
        for key, value in scope.get("headers", ()):
            if key == name:
                return value.decode("latin-1")
    except Exception:  # pragma: no cover - defensive
        pass
    return None


def _is_probe_path(path: str) -> bool:
    return path in _PROBE_PATHS or path.startswith(_PROBE_PATH_PREFIXES)


class ObservabilityMiddleware:
    """Assign a request ID, time the request, count it, log it once."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            # WebSocket and lifespan scopes pass straight through. A WebSocket is
            # a long-lived connection, not a request: recording it in a latency
            # histogram would put a 40-minute observation in the same
            # distribution as a 12ms REST call and make every percentile
            # meaningless. Realtime instrumentation is its own problem.
            await self.app(scope, receive, send)
            return

        method = scope.get("method", "-")
        # Query string deliberately discarded here, at the boundary, so no
        # downstream logging path can reintroduce it. See observability.logging.
        path = scope.get("path", "-")

        request_id = context.resolve_request_id(_header(scope, b"x-request-id"))
        token = context.bind(request_id, method=method, path=path)

        metrics.http_requests_in_flight.inc()
        started = time.perf_counter()
        # Default to 500: if the response never starts (the app raised, the
        # client vanished mid-stream), the request did not succeed, and recording
        # it as a success would be the one lie a metrics system must never tell.
        status_code = 500
        response_started = False

        async def send_wrapper(message: Message) -> None:
            nonlocal status_code, response_started
            if message["type"] == "http.response.start":
                response_started = True
                status_code = message["status"]
                # Stamped on every response, success or failure, so any error a
                # user sees can be quoted back to support and found in the logs.
                MutableHeaders(scope=message)[context.REQUEST_ID_HEADER] = request_id
            await send(message)

        try:
            await self.app(scope, receive, send_wrapper)
        except Exception:
            # An exception that escapes the app means no response was produced by
            # a handler; the server will turn it into a 500. Record it as its own
            # error kind — "the handler blew up" is a different signal from "the
            # handler returned 500" — then re-raise untouched. Swallowing it here
            # would convert a crash into a hung request.
            metrics.record_exception(method, route_template(scope))
            raise
        finally:
            duration_seconds = time.perf_counter() - started
            # The in-flight gauge is decremented FIRST and on its own. It is the
            # one piece of state here that is not self-correcting: a missed
            # decrement is permanent for the life of the process, and a gauge
            # that only ever climbs reads exactly like a saturation incident. Any
            # failure below can lose one sample; this one would poison a
            # dashboard until the next deploy.
            try:
                metrics.http_requests_in_flight.dec()
            except Exception:  # pragma: no cover - defensive
                pass
            # Everything below is best-effort. It runs in a `finally` on the
            # request path, so an exception here would replace a perfectly good
            # response — or mask a real one — with a telemetry bug.
            try:
                route = route_template(scope)
                metrics.record_request(method, route, status_code, duration_seconds)
                if response_started and (
                    not _is_probe_path(path) or obs_logging.log_health_requests()
                ):
                    obs_logging.log_request(
                        method=method,
                        route=route,
                        path=path,
                        status=status_code,
                        duration_ms=duration_seconds * 1000,
                        client_ip=_client_ip(scope),
                        user_agent=_header(scope, b"user-agent"),
                    )
            except Exception:  # pragma: no cover - defensive
                pass
            finally:
                context.reset(token)


def apply_observability(app) -> None:
    """Attach the observability middleware. Call this LAST in `server.py`.

    The one place request instrumentation is wired into the application — the
    same `apply_*(app)` shape `security.cors`, `security.headers`,
    `security.csrf` and `security.rate_limit` already use, so the middleware
    pipeline reads as one consistent list at the bottom of `server.py`.
    """
    app.add_middleware(ObservabilityMiddleware)
