import { AlertTriangle, CheckCircle2, Clock, CircleSlash, HelpCircle, Loader2 } from "lucide-react";
import { ReportState, Freshness, formatAge, formatInstant } from "../../lib/reportProvenance";

/**
 * The Morning Report's honesty strip (D6.9).
 *
 * Renders three facts that the page previously conflated into one line of
 * formatted `generated_at`:
 *
 *   1. WHEN this analysis was generated — and "not recorded" when that is the
 *      truth, never the current time.
 *   2. HOW OLD it is now, as an explicit freshness state rather than a
 *      timestamp the reader has to do arithmetic on.
 *   3. WHETHER a model wrote it, and which one.
 *
 * And it renders the current AI service status *beside* them rather than
 * instead of them. "AI offline" and "report generated at 08:30" are both true
 * at 14:00 and are not in tension — the page said only the first, which read as
 * though the morning's analysis had evaporated.
 *
 * This component decides nothing. Every value comes from `deriveReportStatus`,
 * so the page, the dashboard card and this strip cannot drift apart.
 */

const FRESHNESS_COPY = {
  [Freshness.FRESH]: {
    tone: "var(--gain)",
    icon: CheckCircle2,
    label: "Fresh",
    detail: null,
  },
  [Freshness.STALE]: {
    tone: "#f59e0b",
    icon: AlertTriangle,
    label: "Analysis is stale",
    detail: "Market conditions may have changed since this analysis was generated.",
  },
  [Freshness.VERY_STALE]: {
    tone: "var(--loss)",
    icon: AlertTriangle,
    label: "Analysis is very stale",
    detail:
      "This briefing predates the current trading session. Treat it as a historical record, not as today's read.",
  },
  [Freshness.UNKNOWN]: {
    tone: "var(--text-muted)",
    icon: HelpCircle,
    label: "Age not recorded",
    detail:
      "This report was stored before generation provenance was tracked, so when it was produced is not known.",
  },
  [Freshness.UNAVAILABLE]: {
    tone: "var(--text-muted)",
    icon: CircleSlash,
    label: "No completed analysis",
    detail: null,
  },
};

/** "Generated today at 08:30" — or the honest absence of that fact. */
function GeneratedLine({ status }) {
  const instant = formatInstant(status.completedAt);
  const age = formatAge(status.ageSeconds);

  if (!instant) {
    return (
      <p className="caption font-mono" data-testid="report-generated-at">
        Generation time not recorded
      </p>
    );
  }
  return (
    <p className="caption font-mono" data-testid="report-generated-at">
      Generated {instant}
      {age ? ` · ${age} ago` : ""}
    </p>
  );
}

/**
 * Which model produced the briefing — or the explicit statement that none did.
 *
 * The deterministic case is labelled, not hidden. A briefing assembled from
 * collected numbers is a legitimate product surface; presenting it under an
 * "AI Market Briefing" heading is what was not.
 */
export function BriefingAttribution({ status }) {
  if (status.isAIGenerated) {
    const model = status.aiModel ? ` · ${status.aiModel}` : "";
    return (
      <span className="text-[11px] font-mono" style={{ color: "var(--text-muted)" }}
        data-testid="briefing-attribution">
        Generated by {status.aiProvider || "an AI model"}{model}
      </span>
    );
  }
  return (
    <span className="text-[11px] font-mono" style={{ color: "var(--text-muted)" }}
      data-testid="briefing-attribution">
      Not AI-generated — assembled from the market data collected for this report
    </span>
  );
}

/** Current provider health, stated as a *present-tense* fact about the service. */
function AIServiceLine({ status }) {
  if (status.aiOnline === null) return null;
  const online = status.aiOnline;
  return (
    <span
      className="inline-flex items-center gap-1.5 text-[11px] font-mono"
      style={{ color: online ? "var(--gain)" : "var(--text-muted)" }}
      data-testid="ai-service-status"
    >
      <span
        className="inline-block w-1.5 h-1.5 rounded-full"
        style={{ background: online ? "var(--gain)" : "var(--text-muted)" }}
      />
      AI service {online ? "online" : "offline"}
    </span>
  );
}

export default function ReportProvenance({ status }) {
  if (status.state === ReportState.GENERATING) {
    return (
      <div
        className="flex items-center gap-2 rounded-xl p-3"
        style={{ background: "var(--ai-accent-soft)", border: "1px solid var(--border)" }}
        data-testid="report-provenance"
      >
        <Loader2 size={14} className="animate-spin" style={{ color: "var(--ai-accent)" }} />
        <span className="text-[13px]" style={{ color: "var(--text-secondary)" }}>
          Generating this morning's analysis…
        </span>
      </div>
    );
  }

  const copy = FRESHNESS_COPY[status.freshness] || FRESHNESS_COPY[Freshness.UNKNOWN];
  const Icon = copy.icon;
  // The banner is quiet when the analysis is fresh: a warning shown at every
  // age teaches the reader to ignore it, and then it is not there when it
  // matters. A fresh report gets the timestamp and nothing else.
  const warn = status.freshness !== Freshness.FRESH;

  return (
    <div
      className="rounded-xl p-3 flex flex-col gap-2"
      style={{
        background: warn ? "rgba(245,158,11,0.07)" : "var(--bg-surface)",
        border: `1px solid ${warn ? "rgba(245,158,11,0.25)" : "var(--border)"}`,
      }}
      data-testid="report-provenance"
      data-report-state={status.state}
      data-freshness={status.freshness}
    >
      <div className="flex items-center justify-between flex-wrap gap-2">
        <GeneratedLine status={status} />
        <AIServiceLine status={status} />
      </div>

      {warn && (
        <div className="flex items-start gap-2">
          <Icon size={13} className="mt-0.5 shrink-0" style={{ color: copy.tone }} />
          <div>
            <p className="text-[12px] font-semibold" style={{ color: copy.tone }}
              data-testid="freshness-label">
              {copy.label}
            </p>
            {copy.detail && (
              <p className="text-[12px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                {copy.detail}
              </p>
            )}
          </div>
        </div>
      )}

      <div className="flex items-center gap-2 flex-wrap">
        <BriefingAttribution status={status} />
      </div>

      {/* The observation instant of the numbers, which is NOT the generation
          instant — a report generated at 08:30 from quotes observed at 08:28
          has two different, both-relevant timestamps. Shown only when they are
          genuinely known. */}
      {status.marketDataObservedAt && (
        <span className="text-[11px] font-mono" style={{ color: "var(--text-muted)" }}
          data-testid="market-data-observed-at">
          Market data observed {formatInstant(status.marketDataObservedAt)}
          {status.marketDataTier ? ` · ${status.marketDataTier}` : ""}
        </span>
      )}
    </div>
  );
}

/** The empty/failed states, which must never imply an analysis exists. */
export function ReportUnavailable({ status, note, onRetry }) {
  const MESSAGES = {
    [ReportState.GENERATION_FAILED]:
      "Report generation failed. No AI analysis was produced for this date.",
    [ReportState.AI_UNAVAILABLE_WITHOUT_REPORT]:
      "AI services are offline and no report was successfully generated today.",
    [ReportState.NO_REPORT]:
      "No AI-generated report is available for today yet.",
  };

  return (
    <div className="text-center py-20" style={{ color: "var(--text-muted)" }}
      data-testid="report-unavailable" data-report-state={status.state}>
      <Clock size={40} className="mx-auto mb-3 opacity-40" />
      <p className="body-text mb-2">{MESSAGES[status.state] || MESSAGES[ReportState.NO_REPORT]}</p>
      {/* The backend's own reason, when it gave one. Never a guess, and never a
          provider error string — the API only ever carries user-facing text. */}
      {(note || status.error?.message) && (
        <p className="caption mb-5" data-testid="report-unavailable-note">
          {note || status.error.message}
        </p>
      )}
      {status.aiOnline === false && (
        <p className="caption mb-5" data-testid="ai-offline-note">
          AI service is currently offline.
        </p>
      )}
      <button onClick={onRetry} className="btn-primary">Retry</button>
    </div>
  );
}
