import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { CreditCard, TrendingUp, DollarSign, RefreshCcw, XCircle } from "lucide-react";
import adminService from "../../services/adminService";
import { MetricValue, UnavailablePanel, unavailableReason } from "../../components/ui/Unavailable";
import { PieChart as RPieChart, Pie, Cell, Tooltip, ResponsiveContainer } from "recharts";

const PIE_COLORS = ["#6366F1", "#8B5CF6", "#EC4899", "#F59E0B", "#00D68F", "#06B6D4", "#6B7280"];

const RUPEES = v => `₹${v.toLocaleString("en-IN")}`;

/**
 * PH3.9 — every revenue figure on this page is now explicitly unavailable.
 *
 * The blocker is structural, not a bug to fix here: `db.payments` has no writer
 * anywhere in the codebase and the platform has no payment integration. MRR and
 * ARR were role counts × a hardcoded price (roles are granted by admins without
 * payment, so comped and internal accounts counted as revenue); the 30-day
 * chart was generated by a for-loop with no database access; pending / failed
 * were literal zeros.
 *
 * The plan distribution stays — it is a real count of users by role. It is
 * relabelled to say so: these are *entitlements*, not paying customers, and
 * calling them "Pro Users" on a revenue page was half of how the fabricated MRR
 * looked plausible in the first place.
 */
export default function AdminPayments() {
  const [stats, setStats] = useState(null);
  const [revenue, setRevenue] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    Promise.all([adminService.getPaymentStats(), adminService.getRevenueAnalytics()])
      .then(([s, r]) => { setStats(s.data); setRevenue(r.data); setLoading(false); })
      .catch(() => { setError("Payment statistics could not be loaded."); setLoading(false); });
  }, []);

  if (loading) return <div className="space-y-6"><div className="h-8 w-48 rounded-lg animate-pulse" style={{ background: "var(--border)" }} /><div className="grid grid-cols-4 gap-4">{Array.from({length:4}).map((_,i)=><div key={i} className="h-28 rounded-2xl animate-pulse" style={{background:"var(--bg-surface)"}}/>)}</div></div>;

  if (error) {
    return (
      <div className="space-y-6">
        <h1 className="page-title">Payments & Revenue</h1>
        <div role="alert" className="p-5 rounded-2xl text-sm"
             style={{ background: "var(--bg-card-glass)", border: "1px solid var(--border)", color: "var(--text-secondary)" }}>
          {error}{" "}
          <button onClick={() => window.location.reload()} className="underline" style={{ color: "var(--ai-accent)" }}>Retry</button>
        </div>
      </div>
    );
  }

  const planData = stats?.plan_distribution ? Object.entries(stats.plan_distribution).map(([name, value]) => ({ name, value })) : [];
  const reason = name => unavailableReason(stats, name);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="page-title">Payments & Revenue</h1>
        <p className="page-subtitle mt-1">Financial overview and plan entitlements</p>
      </div>

      {stats?.payments_integration?.integrated === false && (
        <div role="note" className="px-5 py-3 rounded-2xl text-[12px] leading-relaxed"
             style={{ background: "var(--bg-surface)", border: "1px dashed var(--border)", color: "var(--text-secondary)" }}>
          <b>No payment integration.</b> {stats.payments_integration.reason}
        </div>
      )}

      {/* Revenue Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <RevenueCard icon={DollarSign} label="MRR" value={stats?.mrr} format={RUPEES}
                     reason={reason("mrr")} color="#00D68F" />
        <RevenueCard icon={TrendingUp} label="ARR" value={stats?.arr} format={RUPEES}
                     reason={reason("arr")} color="#6366F1" />
        {/* Relabelled: a role count is an entitlement, not a paying customer. */}
        <RevenueCard icon={CreditCard} label="Pro Entitlements" value={stats?.premium_count} color="#8B5CF6" />
        <RevenueCard icon={CreditCard} label="Elite Entitlements" value={stats?.elite_count} color="#EC4899" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Revenue Chart — replaced by an explicit empty state while no capture
            records exist. A zero line across thirty days would still claim we
            measured thirty days. */}
        <motion.div
          initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
          className="lg:col-span-2 p-5 rounded-2xl"
          style={{ background: "var(--bg-card-glass)", backdropFilter: "blur(24px)", border: "1px solid var(--border)" }}
        >
          <h3 className="card-title mb-4">Revenue Trend (30 Days)</h3>
          <UnavailablePanel
            title="Revenue reporting is not available"
            reason={revenue?.note}
            requiredSource={revenue?.required_source}
          />
        </motion.div>

        {/* Plan Distribution — real, and the only real thing on this page. */}
        <motion.div
          initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="p-5 rounded-2xl"
          style={{ background: "var(--bg-card-glass)", backdropFilter: "blur(24px)", border: "1px solid var(--border)" }}
        >
          <h3 className="card-title mb-4">Plan Distribution</h3>
          <div className="h-48">
            <ResponsiveContainer width="100%" height="100%">
              <RPieChart>
                <Pie data={planData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={70} innerRadius={40} paddingAngle={2}>
                  {planData.map((_, i) => <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />)}
                </Pie>
                <Tooltip contentStyle={{ background: "var(--bg-elevated)", border: "1px solid var(--border)", borderRadius: 12, fontSize: 12 }} />
              </RPieChart>
            </ResponsiveContainer>
          </div>
          <div className="space-y-2 mt-2">
            {planData.map((d, i) => (
              <div key={d.name} className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-2.5 h-2.5 rounded-full" style={{ background: PIE_COLORS[i % PIE_COLORS.length] }} />
                  <span className="text-xs capitalize" style={{ color: "var(--text-secondary)" }}>{d.name}</span>
                </div>
                <span className="text-xs font-mono font-semibold" style={{ color: "var(--text-primary)" }}>{d.value}</span>
              </div>
            ))}
          </div>
        </motion.div>
      </div>

      {/* Additional Metrics. These were three literal zeros; `refunds: 0` was
          additionally contradicted by the product, whose refund endpoint wrote
          `payment.refunded` audit records for refunds that never happened. */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <MetricCard label="Pending Payments" value={stats?.pending_payments}
                    reason={reason("pending_payments")} icon={RefreshCcw} color="#F59E0B" />
        <MetricCard label="Refunds" value={stats?.refunds}
                    reason={reason("refunds")} icon={RefreshCcw} color="#8B5CF6" />
        <MetricCard label="Failed Payments" value={stats?.failed_payments}
                    reason={reason("failed_payments")} icon={XCircle} color="#FF6B6B" />
        <MetricCard label="Lifetime Entitlements" value={stats?.lifetime_count}
                    icon={CreditCard} color="#00D68F" />
      </div>
    </div>
  );
}

function RevenueCard({ icon: Icon, label, value, color, format, reason }) {
  return (
    <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} className="p-5 rounded-2xl" style={{ background: "var(--bg-card-glass)", backdropFilter: "blur(24px)", border: "1px solid var(--border)" }}>
      <div className="flex items-center gap-3 mb-3">
        <div className="w-9 h-9 rounded-xl flex items-center justify-center" style={{ background: `${color}15` }}><Icon size={18} style={{ color }} /></div>
        <span className="text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--text-muted)" }}>{label}</span>
      </div>
      <div className="stat-value !text-xl">
        <MetricValue value={value} reason={reason}
                     format={format || (v => (typeof v === "number" ? v.toLocaleString() : v))} />
      </div>
    </motion.div>
  );
}

function MetricCard({ label, value, icon: Icon, color, reason }) {
  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="p-4 rounded-2xl flex items-center gap-4" style={{ background: "var(--bg-card-glass)", backdropFilter: "blur(24px)", border: "1px solid var(--border)" }}>
      <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: `${color}15` }}><Icon size={18} style={{ color }} /></div>
      <div>
        <div className="stat-value !text-lg">
          <MetricValue value={value} reason={reason}
                       format={v => (typeof v === "number" ? v.toLocaleString() : v)} />
        </div>
        <div className="text-xs" style={{ color: "var(--text-muted)" }}>{label}</div>
      </div>
    </motion.div>
  );
}
